name = "server22_iis"
title = "Windows Server 2022 IIS"
os = "Windows Server 2022"
user = "alex"

local = true

version = "2.1.1"


[[check]]
message = "PHP webshell has been deleted"
points = 1
    [[check.pass]]
    type = "PathExistsNot"
    path = "C:/uploads/shl.php"

[[check]]
message = "Powershell reverse shell has been deleted"
points = 1
    [[check.pass]]
    type = "PathExistsNot"
    path = "C:/ProgramData/Microsoft/Windows/Start Menu/Programs/StartUp/shl.exe"

[[check]]
message = "Unauthorized service OpenSSH has been disabled"
points = 1
    [[check.pass]]
    type = "ServiceUpNot"
    name = "ssh-agent"

[[check]]
message = "IIS web service does not run as Local System"
points = 1
    [[check.pass]]
    type = 'FileContainsNot'
    path = 'C:\Windows\System32\inetsrv\config\applicationHost.config'
    value = '<processModel identityType="LocalSystem" />'

[[check]]
message = "All Firewall profiles have been re-enabled"
points = 1
    [[check.pass]]
    type = "FirewallUp"

[[check]]
message = "Real-time protection and Tamper Protection have been re-enabled"
points = 1
    [[check.pass]]
    type = "CommandContains"
    cmd = "Get-MpPreference | Select-Object -Property DisableRealtimeMonitoring"
    value = "False"

[[check]]
message = "Windows Defender exclusion for C:/ does not exist"
points = 1
    [[check.pass]]
    type = "CommandContainsNot"
    cmd = "Get-MpPreference | Select-Object ExclusionPath"
    value = "C:\\"

[[check]]
message = "Python keylogger has been removed"
points = 1
    [[check.pass]]
    type = "PathExistsNot"
    path = "C:/Windows/System32/config/klogger.pyw"

[[check]]
message = "Teamviewer executable removed"
points = 1
    [[check.pass]]
    type = "PathExistsNot"
    path = "C:/Windows/System32/drivers/window.exe" 

[[check]]
message = "Defaced website has been restored from backup"
points = 1
    [[check.pass]]
    type = "FileContainsNot"
    path = "C:/inetpub/wwwroot/index.php"
    value = "YOU HAVE BEEN HACKED!!!"

